[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
version = "0.0.1"
name = "majsoulrpa"
description = "A RPA framework for Mahjong Soul (雀魂)"
license = "MIT"
authors = ["Apricot-S"]
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
]
readme = "README.md"
keywords = ["mahjong", "Mahjong Soul", "Majsoul", "automation", "RPA"]
packages = [{include = "majsoulrpa", from = "src"}]
include = [
    "src/majsoulrpa",
    "src/majsoulrpa/template/**/*",
    "src/majsoulrpa/py.typed",
]

[tool.poetry.dependencies]
python = "^3.11"
imapclient = "*"
mitmproxy = "*"
opencv-python = "*"
playwright = "*"
protobuf = "*"
grpcio = "^1.60.0"
pywinctl = "^0.3"

[tool.poetry.dev-dependencies]
build = "*"
mypy = "*"
ruff = "*"
types-protobuf = "*"

[tool.ruff]
target-version = "py311"
ignore = [
    "ANN101", # missing-type-self
    "ANN102", # missing-type-cls
    "ANN002", # missing-type-args
    "ANN003", # missing-type-kwargs

    "D", # pydocstyle
]
line-length = 79
select = [
    "ALL"
]
src = ["src"]
