[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "majsoulrpa"
description = "A RPA framework for Mahjong Soul (雀魂)"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.11"
keywords = ["mahjong", "Mahjong Soul", "Majsoul", "automation", "RPA"]
authors = [
    {name = "Apricot-S"}
]
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "imapclient",
    "mitmproxy",
    "opencv-python",
    "playwright",
    "protobuf",
    "PyGetWindow",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "build",
    "isort",
    "mypy",
    "ruff",
    "types-protobuf"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.dynamic]
version = {attr = "majsoulrpa._version.__version__"}

[tool.isort]
include_trailing_comma = "True"
line_length = 79
multi_line_output = 3
use_parentheses = "True"
src_paths = ["src", "tests"]

[tool.ruff]
ignore = [
    "ANN101", # missing-type-self
    "ANN102", # missing-type-cls
    "ANN002", # missing-type-args
    "ANN003", # missing-type-kwargs

    "D", # pydocstyle
]
line-length = 79
select = [
    "ALL"
]

[tool.ruff.per-file-ignores]
"./tests/*" = ["S101"]

[tool.pytest.ini_options]
pythonpath = "src"
testpaths = ["tests",]
