[authentication]
email_address = "your_email_address@example.cfg" # Must be 50 characters or less
[browser]
viewport_height = 720 # Support from 720 to 2160
# Support multiple monitors
# The left edge of the primary monitor is 0
# The top of the primary monitor is 0
initial_position = { left = 100, top = 100 }
